### ISSUE TITLE
Does not work on miningrigrentals.com

### ISSUE THREAD

**Issue by aleqx** [Snipa22/xmr-node-proxy#100]
I know yours works only on nodejs-pool pools, but it would be great if you found the time to make it work on MRR. I'd be happy to donate. Right now it dies immediately after receiving the first job from MRR -- which it doesn't undersatnd. MRR also issues `mining.reconnect` for most algos (not sure if it does for cryptonight).

The xmrig-proxy does work on MRR, but I like yours better. It would be nice if you could look into it and update it to work.

Here's the config file:

```json
{
  "pools": [
    {
      "hostname": "eu-de01.miningrigrentals.com",
      "port": 3333,
      "ssl": false,
      "allowSelfSignedSSL": true,
      "share": 100,
      "username": "foo.NNNNN",
      "password": "x",
      "keepAlive": true,
      "coin": "xmr",
      "default": true
    }
  ],
  "listeningPorts": [
    { "port": 20080, "ssl": false, "diff": 1000,  "coin": "xmr" },
    { "port": 20443, "ssl": true , "diff": 1000,  "coin": "xmr" },
    { "port": 23333, "ssl": false, "diff": 5000, "coin": "xmr" },
    { "port": 25555, "ssl": false, "diff": 25000, "coin": "xmr" },
    { "port": 27777, "ssl": false, "diff": 100000, "coin": "xmr" }
  ],
  "bindAddress": "0.0.0.0",
  "developerShare": 0,
  "daemonAddress": "127.0.0.1:18081",
  "coinSettings": {
    "xmr":{
      "minDiff": 100,
      "maxDiff": 300000,
      "shareTargetTime": 30
    },
    "aeon":{
      "minDiff": 100,
      "maxDiff": 300000,
      "shareTargetTime": 30
    }
  }
}
```

Here's the error. This machine has 4 cores.

```
Cluster master setting up 4 workers...
Worker 1161 is online
Worker 1164 is online
Worker 1172 is online
Worker 1167 is online
Master connected to pool: eu-de01.miningrigrentals.com
Started server on port: 20080
Started server on port: 20443
Started server on port: 23333
Started server on port: 25555
Started server on port: 27777
Started server on port: 20080
Started server on port: 20443
Started server on port: 23333
Started server on port: 25555
Started server on port: 27777
Started server on port: 20080
Started server on port: 20443
Started server on port: 23333
Started server on port: 25555
Started server on port: 27777
Started server on port: 20080
Started server on port: 20443
Started server on port: 23333
Started server on port: 25555
Started server on port: 27777

Received new block template from eu-de01.miningrigrentals.com.
buffer.js:195
    throw new errors.TypeError(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:195:11)
    at new Buffer (buffer.js:170:17)
    at new MasterBlockTemplate (/root/dev/xmr-node-proxy/lib/xmr.js:88:19)
    at handleNewBlockTemplate (/root/dev/xmr-node-proxy/proxy.js:724:32)
    at handlePoolMessage (/root/dev/xmr-node-proxy/proxy.js:701:17)
    at Socket.socket.on (/root/dev/xmr-node-proxy/proxy.js:664:17)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:252:13)
    at Socket.Readable.push (_stream_readable.js:213:10)
````

**Comment by Snipa22** [comment]
It never will.  The remote side must support XNP's custom formatting, which is inherently non-compatible with systems like MRR.
