### ISSUE TITLE
Crashes when mining intensecoin

### ISSUE THREAD

**Issue by kim0** [Snipa22/xmr-node-proxy#101]
When trying to mine on https://intense.hashvault.pro/en/#!/help/getting_started the proxy consistently crashes 

```
/app/lib/xmr.js:70
        return cnUtil.convert_blob(this.buffer).toString('hex');
                      ^

Error: Failed to parse block
    at Error (native)
    at BlockTemplate.nextBlob (/app/lib/xmr.js:70:23)
    at Miner.getJob (/app/lib/xmr.js:110:36)
    at process.slaveMessageHandler (/app/proxy.js:118:50)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
/app/lib/xmr.js:70
        return cnUtil.convert_blob(this.buffer).toString('hex');
                      ^

Error: Failed to parse block
    at Error (native)
    at BlockTemplate.nextBlob (/app/lib/xmr.js:70:23)
    at Miner.getJob (/app/lib/xmr.js:110:36)
    at process.slaveMessageHandler (/app/proxy.js:118:50)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:787:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by kim0** [comment]
Someone forked XNP to make it ITNS compatible. The changes seem trivial to me! @Snipa22 you can see the diff here https://github.com/Snipa22/xmr-node-proxy/compare/master...Venthos:master

Hope you can merge those changes soon .. Thanks!

**Comment by Snipa22** [comment]
Too many changes to directly pull into the system.  It would need to be formatted as a standard merge request.

**Comment by kim0** [comment]
@snipa22 .. I can format this as a proper pull request. But since I'm not the original author of that patch, can you confirm just the file lib/itns.js (plus the forknote-util line in package.json) is all that's needed to make XNP compatible with intense ?

**Comment by Snipa22** [comment]
No idea, I don't use ITNS.
