### ISSUE TITLE
Error: Module version mismatch. Expected 46, got 48.

### ISSUE THREAD

**Issue by xguya** [Snipa22/xmr-node-proxy#108]
Hello, I'm getting this error, some idea to fix it ?  

```
2018-02-11 22:57 +01:00: Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at bindings (/home/nodeproxy/xmr-node-proxy/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/node_modules/multi-hashing/index.js:1:99)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

**Comment by xguya** [comment]
Sorry, I forgot to run: source ~/.bashrc

Solved!
