### ISSUE TITLE
proxy start is failing: Cannot read property 'blobForWorker' of null

### ISSUE THREAD

**Issue by ruzickap** [Snipa22/xmr-node-proxy#12]
Hello.

I started the proxy via ```pm2 start proxy.js --name=proxy --log-date-format="YYYY-MM-DD HH:mm Z"```, but then I got this error:

```
$ pm2 logs proxy
[TAILING] Tailing last 15 lines for [proxy] process (change the value with --lines option)
/home/myproxyuser/.pm2/logs/proxy-out-1.log last 15 lines:
1|proxy    | 2017-07-25 08:41 +00:00: Worker 19121 is online
1|proxy    | 2017-07-25 08:41 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-07-25 08:41 +00:00: Worker 19157 is online
1|proxy    | 2017-07-25 08:41 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-07-25 08:41 +00:00: Worker 19193 is online
1|proxy    | 2017-07-25 08:41 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-07-25 08:41 +00:00: Worker 19229 is online
1|proxy    | 2017-07-25 08:41 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-07-25 08:41 +00:00: Worker 19265 is online
1|proxy    | 2017-07-25 08:41 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-07-25 08:41 +00:00: Worker 19301 is online
1|proxy    | 2017-07-25 08:41 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-07-25 08:41 +00:00: Worker 19337 is online
1|proxy    | 2017-07-25 08:41 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-07-25 08:41 +00:00: Worker 19373 is online

/home/myproxyuser/.pm2/logs/proxy-error-1.log last 15 lines:
1|proxy    |     at Worker.emit (events.js:191:7)
1|proxy    |     at ChildProcess.Worker.process.on (cluster.js:53:12)
1|proxy    |     at emitTwo (events.js:106:13)
1|proxy    |     at ChildProcess.emit (events.js:191:7)
1|proxy    | 2017-07-25 08:41 +00:00: TypeError: Cannot read property 'blobForWorker' of null
1|proxy    |     at Object.getMasterJob (/home/myproxyuser/xmr-node-proxy/lib/xmr.js:136:37)
1|proxy    |     at EventEmitter.masterMessageHandler (/home/myproxyuser/xmr-node-proxy/proxy.js:67:50)
1|proxy    |     at emitThree (events.js:116:13)
1|proxy    |     at EventEmitter.emit (events.js:194:7)
1|proxy    |     at Worker.<anonymous> (cluster.js:362:15)
1|proxy    |     at emitTwo (events.js:111:20)
1|proxy    |     at Worker.emit (events.js:191:7)
1|proxy    |     at ChildProcess.Worker.process.on (cluster.js:53:12)
1|proxy    |     at emitTwo (events.js:106:13)
1|proxy    |     at ChildProcess.emit (events.js:191:7)

[STREAMING] Now streaming realtime logs for [proxy] process
```

Any idea what may be wrong?

Thank you...

**Comment by Snipa22** [comment]
The proxy is not receiving a valid blob to work on, check that the pool you're using is fully up to date w/ the nodejs-pool code, as the older node-CN pools do not support this proxy.

**Comment by ruzickap** [comment]
Thanks a lot...
I was using "unsupported" pool.
