### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by mpenagar** [Snipa22/xmr-node-proxy#125]
I got this error while `npm update` on Debian 4.9.65, non AES:

```
make: entering '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function ‘bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)’:
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<anonymous struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
```

**Comment by babyrig** [comment]
I am get this error too

../src/cryptonote_core/cryptonote_basic.h:7:10: fatal error: boost/variant.hpp: No such file or directory

 #include <boost/variant.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
cryptonote.target.mk:108: recipe for target 'Release/obj.target/cryptonote/src/main.o' failed
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util/build'

**Comment by Snipa22** [comment]
First one - You need AES going forwards, and I think you're out of RAM.
Second one - You're missing libboost.

**Comment by babyrig** [comment]
All right G3930 have the AES and running 8GB of ram I think meet these requeriments right ? 

Yeah I found out when I try to do install.sh right way like instructions they failed to install libboost now I am just opened the install.sh and follow step by step to see if have any error on the way

I am stuck now in the npm install process:
the begin of install shows this info:
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

in the end I see this:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cryptonote-util@0.0.3 (node_modules/cryptonote-util):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

can you point me the direction here ?

**Comment by babyrig** [comment]
I read again the warn info and install node-gyp and try install npm again I am stuck again with 

node-gyp rebuild
show this error
yp: binding.gyp not found (cwd: /home/nodeproxy/xmr-node-proxy) while trying to load binding.gyp
gyp ERR! configure error

so I installed node-bindings

and started again from zero stuck here:

 CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function ‘bool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)’:
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^
  CC(target) Release/obj.target/cryptonote/src/crypto/tree-hash.o
  CXX(target) Release/obj.target/cryptonote/src/crypto/crypto.o
../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<unnamed struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);
                                                          ^
cryptonote.target.mk:114: recipe for target 'Release/obj.target/cryptonote/src/crypto/crypto.o' failed
make: *** [Release/obj.target/cryptonote/src/crypto/crypto.o] Error 1
make: Leaving directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.10.17-hiveos
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/node" "/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cryptonote-util@0.0.3 (node_modules/cryptonote-util):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cryptonote-util@0.0.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1


I running node-gyp -v shows v3.0.3 that's the problem ?

**Comment by babyrig** [comment]
I see what I am doing wrong here and installed via npm


npm install -g node-gyp rebuild

and restart from scratch again

now I think I am almost there

npm ERR! argv "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/node" "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/npm" "install" "pm2-logrotate" "--loglevel=error" "--prefix" "/home/nodeproxy/.pm2/modules/pm2-logrotate"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! tarball.destroy is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nodeproxy/npm-debug.log
[PM2][Module] [[[[[ Module installation failure! ]]]]]
[PM2][Module] [RESTORING TO PREVIOUS VERSION]
[PM2][WARN] Applications pm2-logrotate not running, starting...
[PM2] App [pm2-logrotate] launched (1 instances)
[PM2][Module] Monitoring module behavior for potential issue (5secs...)
[PM2][ERROR] Installation failed via NPM, module has been restored to prev version
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬───────────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user      │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼───────────┼──────────┤
│ proxy    │ 1  │ fork │ 0   │ errored │ 18      │ 0      │ 0%  │ 0 B    │ nodeproxy │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴───────────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┬───────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │ user      │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┼───────────┤
│ pm2-logrotate │ N/A     │ N/A        │ online │ 0       │ 0%  │ 14.879 MB   │ nodeproxy │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┴───────────┘
 Use `pm2 show <id|name>` to get more details about an app
