### ISSUE TITLE
[feature] Allow to use pools with self signed SSL certificates

### ISSUE THREAD

**Issue by ruzickap** [Snipa22/xmr-node-proxy#13]
Hello.

I would like to use ssl with pools listed as "supported", but it looks like all pools are using self signed certificates.

So the I'm getting the error from proxy:
```
/home/myproxyuser/.pm2/logs/proxy-error-1.log last 15 lines:
1|proxy    |     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
1|proxy    | 2017-07-25 09:57 +00:00: Error: self signed certificate
1|proxy    |     at Error (native)
1|proxy    |     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
1|proxy    |     at emitNone (events.js:86:13)
1|proxy    |     at TLSSocket.emit (events.js:185:7)
1|proxy    |     at TLSSocket._finishInit (_tls_wrap.js:610:8)
1|proxy    |     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
1|proxy    | 2017-07-25 09:57 +00:00: Error: self signed certificate
1|proxy    |     at Error (native)
1|proxy    |     at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
1|proxy    |     at emitNone (events.js:86:13)
1|proxy    |     at TLSSocket.emit (events.js:185:7)
1|proxy    |     at TLSSocket._finishInit (_tls_wrap.js:610:8)
1|proxy    |     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
````

This is example of my ```config.json```
```
{
  "pools": [
    {
      "hostname": "mine.xmrpool.net",
      "port": 443,
      "ssl": true,
      "share": 80,
      "username": "4...z",
      "password": "x",
      "keepAlive": true,
      "coin": "xmr",
      "default": true
    }
  ],
...
```

Would it be possible to add "feature" to not to verify the TLS certificate?

Something like ```"verify_ssl_certificate": false```

Thank you

**Comment by ruzickap** [comment]
Temporary solution for connecting proxy to pools which are using self signed certificates is adding ```rejectUnauthorized: false``` to ```proxy.js```:

```
this.socket = tls.connect(this.port, this.hostname, { rejectUnauthorized: false }, ()=>{
```

**Comment by Snipa22** [comment]
As of current master, this should be working.  Please test and verify.  You'll need to update your config to use this properly.

**Comment by ruzickap** [comment]
Hello.

I tried for example this config:

```
#It should be "Claymore SSL"
{
  "pools": [
    {
      "hostname": "mine.xmrpool.net",
      "port": 8000,
      "ssl": true,
...
```

But I got only this response when running the proxy (usually when I use non-ssl pool I got more messages like "login/getting new blocks/etc":
```
$ DEBUG="*" node ./proxy.js
Cluster master setting up 1 workers...
Worker 26374 is online
Started server on port: 8443
  workers Worker: 1 currently has 0 miners connected at 0 h/s with an average diff of NaN +0ms
The proxy currently has 0 miners connected at 0 h/s with an average diff of NaN
  workers Worker: 1 currently has 0 miners connected at 0 h/s with an average diff of NaN +15s
The proxy currently has 0 miners connected at 0 h/s with an average diff of NaN
```

It looks like proxy is up, but it doesn't do it's job - because after connecting the miner I got errors (No active block template) on the miner and proxy side.
Connecting the miner directly to the proxy with ssl enabled works fine.

Then I tried mine.xmrpool.net:443 (Claymore SSL Firewall Bypass) with this config:

```
{
  "pools": [
    {
      "hostname": "mine.xmrpool.net",
      "port": 443,
      "ssl": true,
...
```

But I got:

```
$ DEBUG="*" node ./proxy.js
Cluster master setting up 1 workers...
Worker 26433 is online
Master connected to pool: mine.xmrpool.net
  pool Sent {"method":"login","id":1,"params":{"login":"my_monero_wallet_id","pass":"proxytests","agent":"xmr-node-proxy/0.0.1"}} to mine.xmrpool.net +0ms
/home/myproxyuser/xmr-node-proxy/lib/xmr.js:136
    let btBlob = activeBlockTemplate.blobForWorker();
                                    ^

TypeError: Cannot read property 'blobForWorker' of null
    at Object.getMasterJob (/home/myproxyuser/xmr-node-proxy/lib/xmr.js:136:37)
    at EventEmitter.masterMessageHandler (/home/myproxyuser/xmr-node-proxy/proxy.js:70:50)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at Worker.<anonymous> (cluster.js:361:15)
    at emitTwo (events.js:111:20)
    at Worker.emit (events.js:191:7)
    at ChildProcess.Worker.process.on (cluster.js:53:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
```

May I ask you for some sample where SSL/TLS is working for you between pool and the xmr-node-proxy?

Thank you

**Comment by ruzickap** [comment]
I can confirm - it's working fine with the latest version.
Closing the ticket...
