### ISSUE TITLE
Cannot read property 'activeBlocktemplate' of undefined

### ISSUE THREAD

**Issue by mouradski** [Snipa22/xmr-node-proxy#131]
/home/nodeproxy/.pm2/logs/proxy-out-1.log last 15 lines:
1|proxy    | 2018-04-08 22:40 +02:00: Master connected to pool: pool.supportxmr.com
1|proxy    | 2018-04-08 22:40 +02:00: Received new block template from xmr-donations.snipanet.com
1|proxy    | 2018-04-08 22:40 +02:00: Received new block template from pool.supportxmr.com
1|proxy    | 2018-04-08 22:40 +02:00: Started server on port: 7000
1|proxy    | 2018-04-08 22:40 +02:00: Started server on port: 5555
1|proxy    | 2018-04-08 22:40 +02:00: Started server on port: 3333
1|proxy    | 2018-04-08 22:40 +02:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-08 22:40 +02:00: Worker 2353 is online
1|proxy    | 2018-04-08 22:40 +02:00: Master connected to pool: pool.supportxmr.com
1|proxy    | 2018-04-08 22:40 +02:00: Master connected to pool: xmr-donations.snipanet.com
1|proxy    | 2018-04-08 22:40 +02:00: Received new block template from pool.supportxmr.com
1|proxy    | 2018-04-08 22:40 +02:00: Received new block template from xmr-donations.snipanet.com
1|proxy    | 2018-04-08 22:40 +02:00: Started server on port: 7000
1|proxy    | 2018-04-08 22:40 +02:00: Started server on port: 5555
1|proxy    | 2018-04-08 22:40 +02:00: Started server on port: 3333

1|proxy    | 2018-04-08 22:40 +02:00: Received new block template from pool.supportxmr.com
1|proxy    | 2018-04-08 22:41 +02:00: The proxy currently has 0 miners connected at 0 h/s with an average diff of NaN
1|proxy    | 2018-04-08 22:41 +02:00: Received new block template from pool.supportxmr.com
1|proxy    | 2018-04-08 22:41 +02:00: Received new block template from xmr-donations.snipanet.com
1|proxy    | 2018-04-08 22:41 +02:00: The proxy currently has 0 miners connected at 0 h/s with an average diff of NaN
1|proxy    | 2018-04-08 22:41 +02:00: TypeError: Cannot read property 'activeBlocktemplate' of undefined
1|proxy    |     at new Miner (/home/nodeproxy/v7/xxx/proxy.js:766:31)
1|proxy    |     at handleMinerData (/home/nodeproxy/v7/xxx/proxy.js:857:21)
1|proxy    |     at handleMessage (/home/nodeproxy/v7/xxx/proxy.js:992:13)
1|proxy    |     at Socket.<anonymous> (/home/nodeproxy/v7/xxx/proxy.js:1050:25)
1|proxy    |     at emitOne (events.js:96:13)
1|proxy    |     at Socket.emit (events.js:188:7)
1|proxy    |     at readableAddChunk (_stream_readable.js:176:18)
1|proxy    |     at Socket.Readable.push (_stream_readable.js:134:10)
1|proxy    |     at TCP.onread (net.js:548:20)
1|proxy    | 2018-04-08 22:41 +02:00: Worker 2353 died with code: 1, and signal: null

`"pools": [
    {
      "hostname": "pool.supportxmr.com",
      "port": 5555,
      "ssl": false,
      "allowSelfSignedSSL": false,
      "share": 80,
      "username": "49mzBJckUwCDsyLDWUSnrTQXieoei1GUxBoayB2rQeUABof2iuVMoamRNYXHE75tx5Fr4Tz6KqobA5H1Rr93ESA8MVM1QiJ",
      "password": "x",
      "keepAlive": false,
      "coin": "xmr",
      "default": false
    }
  ]`

Thanx for your work :)

**Comment by Snipa22** [comment]
Set default to true.
