### ISSUE TITLE
Prompt in what an error?

### ISSUE THREAD

**Issue by poloniy214** [Snipa22/xmr-node-proxy#136]
2018-04-25 03:01 +03:00: Error: Cannot find module 'cryptonote-util'
1|proxy    |     at Function.Module._resolveFilename (module.js:469:15)
1|proxy    |     at Function.Module._load (module.js:417:25)
1|proxy    |     at Module.require (module.js:497:17)
1|proxy    |     at require (internal/module.js:20:19)
1|proxy    |     at Object.<anonymous> (/home/shtorm/xmr-node-proxy/lib/xmr.js:3:16)
1|proxy    |     at Module._compile (module.js:570:32)
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)
1|proxy    |     at Function.Module._load (module.js:438:3)

**Comment by bobbieltd** [comment]
That util seems not be installed
cd ~/xmr-node-proxy
git pull
npm install

**Comment by poloniy214** [comment]
npm install
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/shtorm/.nvm/versions/node/v6.9.                                                                                        2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                        s.js:215:12)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/home/shtorm/.nvm/versions/node/v6.9.2/bin/node" "/home/shtorm                                                                                        /.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-g                                                                                        yp.js" "rebuild"
gyp ERR! cwd /home/shtorm/xmr-node-proxy/node_modules/cryptonote-util
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by bobbieltd** [comment]
I can not see any info about CPU. Run this :
cat /proc/cpuinfo

**Comment by poloniy214** [comment]
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 6
model name      : QEMU Virtual CPU version 2.5+
stepping        : 3
microcode       : 0x1
cpu MHz         : 2400.084
cache size      : 16384 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl xtopology pni cx16 x2apic hypervisor lahf_lm
bugs            :
bogomips        : 4800.16
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

**Comment by bobbieltd** [comment]
It seems there is not AES-NI with your CPU emulation. 
You can try this non-AES util multi hashing in package.json : "multi-hashing": "git+https://github.com/grunjol/node-multi-hashing.git#Nan-2.0”
And npm update or npm install
I have tested it. Give it a try.

**Comment by poloniy214** [comment]
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/shtorm/xmr-node-proxy
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

**Comment by poloniy214** [comment]
2018-04-25 03:01 +03:00: Error: Cannot find module 'cryptonote-util'
1|proxy | at Function.Module._resolveFilename (module.js:469:15)
1|proxy | at Function.Module._load (module.js:417:25)
1|proxy | at Module.require (module.js:497:17)
1|proxy | at require (internal/module.js:20:19)
1|proxy | at Object. (/home/shtorm/xmr-node-proxy/lib/xmr.js:3:16)
1|proxy | at Module._compile (module.js:570:32)
1|proxy | at Object.Module._extensions..js (module.js:579:10)
1|proxy | at Module.load (module.js:487:32)
1|proxy | at tryModuleLoad (module.js:446:12)
1|proxy | at Function.Module._load (module.js:438:3)

**Comment by bobbieltd** [comment]
Can you fork this repo ? I'll make PR (changes) for your repo so you can try to install

**Comment by poloniy214** [comment]
which add repositories?

**Comment by bobbieltd** [comment]
Ouff, it seems hard for you. You should try to rent another VPS (with x64 AES-NI CPU).

**Comment by poloniy214** [comment]
gyp: binding.gyp not found (cwd: /home/shtorm/xmr-node-proxy/node_modules/node-pre-gyp/bin) while trying to load binding.gyp 
find . binding ?
