### ISSUE TITLE
Can xmr-node-proxy be one miner of xmr-node-proxy?

### ISSUE THREAD

**Issue by z1n** [Snipa22/xmr-node-proxy#138]
As the title, I tried but it seems that there is a problem to phrase the block.

>  TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
> 0|proxy    |     at fromObject (buffer.js:262:9)
> 0|proxy    |     at Function.Buffer.from (buffer.js:101:10)
> 0|proxy    |     at new Buffer (buffer.js:80:17)
> 0|proxy    |     at new MasterBlockTemplate (/home/zhanglin/learn/btc/xmr-node-proxy/lib/xmr.js:88:19)
> 0|proxy    |     at handleNewBlockTemplate (/home/zhanglin/learn/btc/xmr-node-proxy/proxy.js:717:32)
> 0|proxy    |     at handlePoolMessage (/home/zhanglin/learn/btc/xmr-node-proxy/proxy.js:694:17)
> 0|proxy    |     at Socket.socket.on.e (/home/zhanglin/learn/btc/xmr-node-proxy/proxy.js:657:17)
> 0|proxy    |     at emitOne (events.js:96:13)
> 0|proxy    |     at Socket.emit (events.js:188:7)
> 0|proxy    |     at readableAddChunk (_stream_readable.js:176:18)

**Comment by bobbieltd** [comment]
It looks quite the same issue on my repo. You connect proxy to non nodejs-pool. XNP proxy only works with nodejs-pool (check the footer of pool website if there is powered by nodejd-pool ...)

**Comment by appkoders** [comment]
It only works on nodejs-pool since the pool sends a different data(job) if the miner that connects to it is using the user agent `xmr-node-proxy`.

https://github.com/Snipa22/nodejs-pool/blob/4853b1b98338c2f5a1934fab5c446f38777e1318/lib/pool.js#L225

**Comment by bobbieltd** [comment]
@appkoders Thanks for your info. I like your explanation.
@z1n  So the proxy need to be modified. What is the use case of multiple level proxy over proxy ?
