### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by 798654350** [Snipa22/xmr-node-proxy#139]
`nodeproxy@iZ0ubppk8toxslZ:~/xmr-node-proxy$ pm2 logs proxy
[TAILING] Tailing last 15 lines for [proxy] process (change the value with --lines option)
/home/nodeproxy/.pm2/logs/proxy-out-1.log last 15 lines:
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...
1|proxy    | 2018-04-26 19:09 +08:00: Cluster master setting up 1 workers...

/home/nodeproxy/.pm2/logs/proxy-error-1.log last 15 lines:
1|proxy    |     at bindings (/home/nodeproxy/xmr-node-proxy/node_modules/bindings/bindings.js:81:44)
1|proxy    |     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/index.js:1:99)
1|proxy    |     at Module._compile (module.js:410:26)
1|proxy    |     at Object.Module._extensions..js (module.js:417:10)
1|proxy    | 2018-04-26 19:09 +08:00: Error: Module version mismatch. Expected 46, got 48.
1|proxy    |     at Error (native)
1|proxy    |     at Object.Module._extensions..node (module.js:435:18)
1|proxy    |     at Module.load (module.js:344:32)
1|proxy    |     at Function.Module._load (module.js:301:12)
1|proxy    |     at Module.require (module.js:354:17)
1|proxy    |     at require (internal/module.js:12:17)
1|proxy    |     at bindings (/home/nodeproxy/xmr-node-proxy/node_modules/bindings/bindings.js:81:44)
1|proxy    |     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/node_modules/cryptonight-hashing/index.js:1:99)
1|proxy    |     at Module._compile (module.js:410:26)
1|proxy    |     at Object.Module._extensions..js (module.js:417:10)
`

**Comment by mouradski** [comment]
same error here :(
