### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by TheRogue27** [Snipa22/xmr-node-proxy#142]
proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)1|proxy    |     at Function.Module._load (module.js:438:3)
1|proxy    | 2018-05-16 16:10 +00:00: Error: Cannot find module 'cryptonote-util'
1|proxy    |     at Function.Module._resolveFilename (module.js:469:15)
1|proxy    |     at Function.Module._load (module.js:417:25)
1|proxy    |     at Module.require (module.js:497:17)
1|proxy    |     at require (internal/module.js:20:19)
1|proxy    |     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:3:16)
1|proxy    |     at Module._compile (module.js:570:32)
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)1|proxy    |     at Function.Module._load (module.js:438:3)
1|proxy    | 2018-05-16 16:10 +00:00: Error: Cannot find module 'cryptonote-util'
1|proxy    |     at Function.Module._resolveFilename (module.js:469:15)
1|proxy    |     at Function.Module._load (module.js:417:25)
1|proxy    |     at Module.require (module.js:497:17)
1|proxy    |     at require (internal/module.js:20:19)
1|proxy    |     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:3:16)
1|proxy    |     at Module._compile (module.js:570:32)
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)1|proxy    |     at Function.Module._load (module.js:438:3)

Any ideea?

**Comment by TheRogue27** [comment]
Crap...i just saw that 17.10 is not supported
