### ISSUE TITLE
Cannot find module 'cryptonight-hashing

### ISSUE THREAD

**Issue by xiaoyueraymond** [Snipa22/xmr-node-proxy#145]
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)
1|proxy    |     at Function.Module._load (module.js:438:3)
1|proxy    | 2018-06-01 19:34 +08:00: Error: Cannot find module 'cryptonight-hashing'
1|proxy    |     at Function.Module._resolveFilename (module.js:469:15)
1|proxy    |     at Function.Module._load (module.js:417:25)
1|proxy    |     at Module.require (module.js:497:17)
1|proxy    |     at require (internal/module.js:20:19)
1|proxy    |     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:2:22)
1|proxy    |     at Module._compile (module.js:570:32)
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)
1|proxy    |     at Function.Module._load (module.js:438:3)

**Comment by bobbieltd** [comment]
cd ~/xmr-node-proxy
npm install
Check if any error with cryptonight-hashing util.
