### ISSUE TITLE
Can't see workers multiHashing.randomx is not a function

### ISSUE THREAD

**Issue by jmusac** [Snipa22/xmr-node-proxy#166]
After upgrading proxy for RandomX algo i can't see my  workers on pool.supporxmr.com pool. 
On proxy (pm2 monit) i can see that miners are connected.
Also sometimes during monitoring (pm2 monit) i get this error

TypeError: multiHashing.randomx is not a function                                          
at Object.processShare (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:203:27)              
at handleMinerData (/home/nodeproxy/xmr-node-proxy/proxy.js:930:49)                    
at handleMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:992:13)                     
at Socket.<anonymous> (/home/nodeproxy/xmr-node-proxy/proxy.js:1050:25)                
at emitOne (events.js:96:13)                                                           
at Socket.emit (events.js:188:7)                                                       
at readableAddChunk (_stream_readable.js:176:18)                                       
at Socket.Readable.push (_stream_readable.js:134:10)                                   
at TCP.onread (net.js:548:20)                                                          
Worker 2638 died with code: 1, and signal: null

**Comment by SuperBobb** [comment]
Hi jmusac,
I have the same issue, cannot see my workers on the pool.supportxmr.com pool (although I do no have that TypeError message).
Have you solved this issue? What was wrong?
What should be modified in the config.json file?
