### ISSUE TITLE
Install script is broken

### ISSUE THREAD

**Issue by Renemen64** [Snipa22/xmr-node-proxy#167]
The install script by default install latest version pm2 (at now it is 4.20), this version depending a node-js v8 or higer, but script install v6.9.2. 
So I fix it by replace "npm install -g pm2" to "npm install -g pm2@3.5.1"
Sorry for my bad english.

**Comment by loopyd** [comment]
OP is correct you receive the following error during compile:

`/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/pm2/node_modules/chalk/source/index.js:103
        ...styles,
        ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/pm2/constants.js:10:14)
    at Module._compile (module.js:570:32)
/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/pm2/node_modules/chalk/source/index.js:103
        ...styles,
        ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/pm2/constants.js:10:14)
    at Module._compile (module.js:570:32)
chown: cannot access '/home/nodeproxy/.pm2': No such file or directory
Installing pm2-logrotate in the background!
You're setup with a shiny new proxy!  Now, go configure it and have fun.
nodeproxy@PawCloud-XMR-Proxy:~$ /home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/pm2/node_modules/chalk/source/index.js:103
        ...styles,
        ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/pm2/constants.js:10:14)
    at Module._compile (module.js:570:32)`
    
    
    After applying this fix you can install properly.   Thank you!  I will make MPR on this shortly.
