### ISSUE TITLE
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by therealseeku** [Snipa22/xmr-node-proxy#39]
Ubuntu 16.04.3 LTS minimal install 

After changing the line in package.json to
` "multi-hashing": "git://github.com/clintar/node-multi-hashing.git#Nan-2.0",`
everything worked fine

**Comment by Snipa22** [comment]
Your system doesn't have AES-NI, the old clintar version doesn't use it.

**Comment by andrebardo** [comment]
The log says:
```
3|proxy    | 2017-11-22 05:25 -02:00: Cluster master setting up 4 workers...
3|proxy    | 2017-11-22 05:25 -02:00: Error: Cannot find module 'multi-hashing'
3|proxy    |     at Function.Module._resolveFilename (module.js:469:15)
3|proxy    |     at Function.Module._load (module.js:417:25)
3|proxy    |     at Module.require (module.js:497:17)
3|proxy    |     at require (internal/module.js:20:19)
3|proxy    |     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:2:22)
3|proxy    |     at Module._compile (module.js:570:32)
3|proxy    |     at Object.Module._extensions..js (module.js:579:10)
3|proxy    |     at Module.load (module.js:487:32)
3|proxy    |     at tryModuleLoad (module.js:446:12)
3|proxy    |     at Function.Module._load (module.js:438:3)
```
So I tried to change the package.json as suggested, and did the 
`nodeproxy@kurumin:~/xmr-node-proxy$ npm install package.json `

I just got this:
```
nodeproxy@kurumin:~/xmr-node-proxy$ npm install package.json 
npm ERR! not a package /home/nodeproxy/xmr-node-proxy/package.json
npm ERR! addLocal Could not install /home/nodeproxy/xmr-node-proxy/package.json
npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/node" "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/npm" "install" "package.json"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path /tmp/npm-16136-886e2156/unpack-44eeddf0/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/npm-16136-886e2156/unpack-44eeddf0/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/npm-16136-886e2156/unpack-44eeddf0/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nodeproxy/xmr-node-proxy/npm-debug.log
```
the requested file: [npm-debug.log](https://github.com/Snipa22/xmr-node-proxy/files/1494921/npm-debug.log)
