### ISSUE TITLE
Cannot find module 'cryptonote-util'

### ISSUE THREAD

**Issue by radiogena** [Snipa22/xmr-node-proxy#50]
fresh unbuntu 16.04.3 install. have this issue, how to fix?

2017-10-04 15:29 +03:00: Error: Cannot find module 'cryptonote-util'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:3:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by radiogena** [comment]
nodeproxy@nodeproxy:~/xmr-node-proxy$ npm install cryptonote-util
npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: Cloning into bare repository '/home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a'...
npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: github.com[0: 192.30.253.112]: errno=Connection timed out
npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: github.com[1: 192.30.253.113]: errno=Connection timed out
npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "cryptonote-util"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a
npm ERR! Cloning into bare repository '/home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Connection timed out
npm ERR! github.com[1: 192.30.253.113]: errno=Connection timed out
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nodeproxy/xmr-node-proxy/npm-debug.log

**Comment by hriad** [comment]
It's in the README.

If your system doesn't have AES-NI, then it will throw an error during the node-multi-hashing install, as this is AES-NI required. If this is the case, go ahead and change the following line: "multi-hashing": "git+https://github.com/Snipa22/node-multi-hashing-aesni.git", to: "multi-hashing": "git://github.com/clintar/node-multi-hashing.git#Nan-2.0", In your packages.json, then do a npm install, and it should pass.

**Comment by cooler0918** [comment]
I have the same issue with it not finding 'cryptonote-util'.  When I try to do an 'npm install'  I get this error.

> make: Entering directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
  CXX(target) Release/obj.target/cryptonote/src/cryptonote_core/cryptonote_format_utils.o
../src/cryptonote_core/cryptonote_format_utils.cpp: In function âbool cryptonote::check_proof_of_work(const cryptonote::block&, cryptonote::difficulty_type, crypto::hash&)â:
../src/cryptonote_core/cryptonote_format_utils.cpp:938:3: warning: no return statement in function returning non-void [-Wreturn-type]
   }
   ^

>

**Comment by minereobot1** [comment]
> nodeproxy@nodeproxy:~/xmr-node-proxy$ npm install cryptonote-util
> npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: Cloning into bare repository '/home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a'...
> npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: fatal: unable to connect to github.com:
> npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: github.com[0: 192.30.253.112]: errno=Connection timed out
> npm ERR! git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a: github.com[1: 192.30.253.113]: errno=Connection timed out
> npm ERR! Linux 4.4.0-96-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "cryptonote-util"
> npm ERR! node v4.2.6
> npm ERR! npm v3.5.2
> npm ERR! code 128
> 
> npm ERR! Command failed: git clone --template=/home/nodeproxy/.npm/_git-remotes/_templates --mirror git://github.com/Snipa22/node-cryptonote-util.git /home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a
> npm ERR! Cloning into bare repository '/home/nodeproxy/.npm/_git-remotes/git-github-com-Snipa22-node-cryptonote-util-git-xmr-Nan-2-0-12c8302a'...
> npm ERR! fatal: unable to connect to github.com:
> npm ERR! github.com[0: 192.30.253.112]: errno=Connection timed out
> npm ERR! github.com[1: 192.30.253.113]: errno=Connection timed out
> npm ERR!
> npm ERR!
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR! https://github.com/npm/npm/issues
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! /home/nodeproxy/xmr-node-proxy/npm-debug.log

Nobody gonna help you here buddy, this is a page only for suckers
