### ISSUE TITLE
Issue whilst installing the cyptonote-utils package

### ISSUE THREAD

**Issue by MossFrog** [Snipa22/xmr-node-proxy#58]
![errorlog](https://user-images.githubusercontent.com/15126587/32105030-a7fc0fd2-bb2f-11e7-91b8-7354417fe34e.PNG)

I have uploaded the image, anyone have any suggestions?
The output message appears to be ELIFECYCLE, ive tried updating npm and node.js to no avail.

**Comment by spanias** [comment]
+1 for this one. I have the same issue on a clean ubuntu box.

**Comment by spanias** [comment]
+1 on this. Having the same issue.

**Comment by Snipa22** [comment]
What version of Ubuntu?  This looks like a GCC compile bug.  Keep in mind, this project is explicitly targeted at Ubuntu 16.04 LTS x64

**Comment by spanias** [comment]
Ubuntu 17.10 64bit

lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
uname -a
4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

I also removed AES-NI from packages.json

The problem is with the compilation of cryptonote-util:
../src/crypto/crypto.cpp: In function ‘std::size_t crypto::rs_comm_size(std::size_t)’:
../src/crypto/crypto.cpp:224:58: error: value-initialization of incomplete type ‘crypto::rs_comm::<unnamed struct> []’
     return sizeof(rs_comm) + pubs_count * sizeof(rs_comm().ab[0]);

I guess I must install another vm. :/

**Comment by Snipa22** [comment]
> Description: Ubuntu 17.10

This is not supported.  Use Ubuntu 16.04 LTS.  Using non-LTS for anything you plan on running traffic to is insane.

**Comment by spanias** [comment]
Yes, I got that much. 👍   Thank you Snipa.

Will try making a docker container out of this when I get some time. That should make deployment easier. :)

**Comment by praeluceo** [comment]
I also have an error installing cryptonote-util, but on Ubuntu 16.04:

`[bignum] Success: "/home/nodeproxy/xmr-node-proxy/node_modules/bignum/binding/bignum.node" is installed via remote

> cryptonote-util@0.0.3 install /home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util/build'
  CXX(target) Release/obj.target/cryptonote/src/main.o
In file included from ../src/main.cc:8:0:
../src/cryptonote_core/cryptonote_basic.h:7:29: fatal error: boost/variant.hpp: No such file or directory
compilation terminated.
cryptonote.target.mk:108: recipe for target 'Release/obj.target/cryptonote/src/main.o' failed
make: *** [Release/obj.target/cryptonote/src/main.o] Error 1
make: Leaving directory '/home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.10.0-38-generic
gyp ERR! command "/home/nodeproxy/.nvm/versions/node/v6.9.2/bin/node" "/home/nodeproxy/.nvm/versions/node/v6.9.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
`
$ uname -a
Linux bitcoin 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by untoreh** [comment]
is the only reason for lack of support the old libboost required by cryptonote-util ?

**Comment by phubbard91** [comment]
I'm having this exact problem. I've made sure my user has sudo privileges. Running a completely new DigitalOcean Ubuntu 16.04.4 LTS Droplet. I've tried the walk through several times and I'm still getting this error. Any suggestions?
