### ISSUE TITLE
error with connecting new miner?

### ISSUE THREAD

**Issue by Falesco** [Snipa22/xmr-node-proxy#61]
x proxy > 2017-11-03 04:17 -04:00: Worker 10806 died with code: 1, and signal: null                                                            x
x                                                            xx proxy > 2017-11-03 04:17 -04:00: Starting a new worker                                                                                       x
x                                                            xx proxy > 2017-11-03 04:17 -04:00: Worker 10866 is online                                                                                      x
x                                                            xx proxy > 2017-11-03 04:17 -04:00: Started server on port: 8080                                                                                x
x                                                            xx proxy > 2017-11-03 04:17 -04:00: Started server on port: 8443                                                                                x
x                                                            xx proxy > 2017-11-03 04:17 -04:00: Started server on port: 3333                                                                                x
x                                                            xx proxy > 2017-11-03 04:17 -04:00: The proxy currently has 0 miners connected at 0 h/s with an average diff of NaN                             x
x                                                            xx proxy > 2017-11-03 04:17 -04:00: TypeError: Cannot read property 'activeBlocktemplate' of undefined                                          x
x                                                            xx proxy >     at new Miner (/home/nodeproxy/xmr-node-proxy/proxy.js:766:31)                                                                    x
x                                                            xx proxy >     at handleMinerData (/home/nodeproxy/xmr-node-proxy/proxy.js:857:21)                                                              x
x                                                            xx proxy >     at handleMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:992:13)                                                                x
x                                                            xx proxy >     at Socket.<anonymous> (/home/nodeproxy/xmr-node-proxy/proxy.js:1050:25)                                                          x
x                                                            xx proxy >     at emitOne (events.js:96:13)                                                                                                     x
x                                                            xx proxy >     at Socket.emit (events.js:188:7)                                                                                                 x
x                                                            xx proxy >     at readableAddChunk (_stream_readable.js:176:18)                                                                                 x
x                                                            xx proxy >     at Socket.Readable.push (_stream_readable.js:134:10)                                                                             x
x                                                            xx proxy >     at TCP.onread (net.js:548:20)                                                                                                    x
x                                                            xx proxy > 2017-11-03 04:17 -04:00: Worker 10833 died with code: 1, and signal: null

**Comment by Snipa22** [comment]
Whatever you're connecting to isn't handing you a block template in time.  Make sure you set one of your pools to default: true.
