### ISSUE TITLE
Can we use it with other coins? ETN?

### ISSUE THREAD

**Issue by pinkflozd** [Snipa22/xmr-node-proxy#62]
hello. i tried to connect the proxy to a ETN pool but im getting the following error:
`
proxy > 2017-11-24 13:41 +01:00: Master connected to pool: pool.electroneum.space
proxy > 2017-11-24 13:41 +01:00: Received new block template from pool.electroneum.space
proxy > 2017-11-24 13:41 +01:00: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
proxy >     at fromObject (buffer.js:262:9)
proxy >     at Function.Buffer.from (buffer.js:101:10)
proxy >     at new Buffer (buffer.js:80:17)
proxy >     at new MasterBlockTemplate (/home/miner/xmr-node-proxy/lib/xmr.js:88:19)
proxy >     at handleNewBlockTemplate (/home/miner/xmr-node-proxy/proxy.js:717:32)
proxy >     at handlePoolMessage (/home/miner/xmr-node-proxy/proxy.js:694:17)
proxy >     at Socket.socket.on.e (/home/miner/xmr-node-proxy/proxy.js:657:17)
proxy >     at emitOne (events.js:96:13)
proxy >     at Socket.emit (events.js:188:7)
proxy >     at readableAddChunk (_stream_readable.js:176:18)
PM2 > App [proxy] with id [1] and pid [11939], exited with code [1] via signal [SIGINT]
PM2 > Starting execution sequence in -fork mode- for app name:proxy id:1
PM2 > App name:proxy id:1 online
`

can the proxy me made to work wit ETN or other coins?

**Comment by jasminors** [comment]
I am interested in this too and I am getting the same error for the us-etn-stats.hashparty.io pool.I've tried with another two ETN pools and the same results.monero pool seems fine with no issues

**Comment by Snipa22** [comment]
Pool has to support it.  Someone was working with me to have me extend the pool and proxy for ETN, but then someone on the ETN core team killed the project.  So no, there's no support for ETN at this time, unless you find an ETN pool that's using NodeJS-Pool.

**Comment by ddebin** [comment]
There is at least https://electroneum.hashvault.pro/ which is using nodejs-pool for ETN.

**Comment by jasminors** [comment]
@Snipa22 Thanks for the update @ddebin  Thanks for the link

**Comment by pinkflozd** [comment]
@Snipa22 Thanks for the info... So probably also other pools and other coins running cryptonote-universal-pool v1.1.6 won't work with your proxy?

**Comment by mercenaruss** [comment]
@pinkflozd @jasminors you tried to push Proxy to this pool(https://electroneum.hashvault.pro/)?
Worked out?

**Comment by pinkflozd** [comment]
@mercenaruss yes it works... any pool running nodejs-pool works with the proxy

**Comment by mercenaruss** [comment]
@pinkflozd I have some issues with it,tried 2 pools with nodejs-pool and i have errors.
1. pm2 stop proxy - To stop proxy 
2. Edit config.json , where i change just pool,port and wallet(to ETN) ,save file
3. pm2 start proxy, proxy is up and working but with lots of errors

Error:
2017-12-08 00:56 +00:00: TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at new MasterBlockTemplate (/home/nodeproxy/xmr-node-proxy/lib/xmr.js:88:19)
    at handleNewBlockTemplate (/home/nodeproxy/xmr-node-proxy/proxy.js:717:32)
    at handlePoolMessage (/home/nodeproxy/xmr-node-proxy/proxy.js:694:17)
    at Socket.socket.on.e (/home/nodeproxy/xmr-node-proxy/proxy.js:657:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)

What this can be? NPN is crashing.
https://github.com/npm/npm/issues/19350

**Comment by Snipa22** [comment]
You pointed it at a non nodejs-pool based pool.  The system isn't returning back the data expected, so it's freaking out and dying.  Most ETN pools do not support the proxy.

**Comment by mercenaruss** [comment]
@Snipa22 this you explained up , but this pool(https://electroneum.hashvault.pro/) and another one (https://easyhash.io)  is based on your xmr-node-pool and owner is confirming it,people reporting it like working.
So I'm just confused.

**Comment by Snipa22** [comment]
@mercenaruss https://easyhash.io/pools/electroneum doesn't appear to be based on NodeJS-pool.  In fact, given the stats response, I can almost guarantee you it's built on Node-Cryptonote-Pool.

**Comment by mercenaruss** [comment]
@Snipa22 thank you very much.
Now (https://electroneum.hashvault.pro/) is 100% is proven to be NodeJs-Pool.Had a discussion by 4 a.m. with admin of pool. He confirmed. But still the same error.
Will try to submit more logs.

**Comment by ddebin** [comment]
It works for me with https://electroneum.hashvault.pro/.

**Comment by Techjar** [comment]
https://electroneum.hashvault.pro/ is also not working for me, it just spits out `Error response from pool pool.electroneum.hashvault.pro: {"code":-1,"message":"No active block template"}` every once in a while.

**Comment by mercenaruss** [comment]
@Techjar yh,have the same issue,bu this is a pool problem,admins there have just issues all the time.
Anyway a general integration of ETN to xmr-node-proxy is more welcomed ,so any pool can be used and not to rely on one(because only one at the moment is working with nodejs) hope to have a future support from @Snipa22

**Comment by Snipa22** [comment]
XNP requires NodeJS-Pool updates for integration.  If ETN miners are serious about wanting this, I'll make it easy.  Raise 100k ETN, and I'll do the NodeJS-Pool and XNP integrations.  If it looks like y'all are half-serious, I'll put up an address funds can be sent to.

**Comment by DaveLong** [comment]
I have managed to get this working on an etn pool here:  https://etn.luckypool.io

**Comment by NanoBytesInc** [comment]
Would i use the xmr.js file? Or are there tweaks needed to make a etn.js?

**Comment by DaveLong** [comment]
I copied xmr.js to ent.js and tweaked a few things (cannot remember exactly what now as I didn't run XNP for more than a few days - saw a significant drop in hash rate through XNP as oppossed to having miners connected directly to the pool.) I may well have not had an optimal configuration, but I didn't have time to experiment so decided to connect miners directly to the pool instead.
