### ISSUE TITLE
Unexpected token , in JSON at position 76

### ISSUE THREAD

**Issue by tjosm** [Snipa22/xmr-node-proxy#63]
Tried to install XNP on a 3GB DigitalOcean droplet. Getting this error on pm2 logs

```
1|proxy    |     at require (internal/module.js:20:19)
1|proxy    |     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/proxy.js:9:17)
1|proxy    |     at Module._compile (module.js:570:32)
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
1|proxy    | 2017-11-28 04:12 +00:00: SyntaxError: /home/nodeproxy/xmr-node-proxy/config.json: Unexpected token , in JSON at position 76
1|proxy    |     at Object.parse (native)
1|proxy    |     at Object.Module._extensions..json (module.js:587:27)
1|proxy    |     at Module.load (module.js:487:32)
1|proxy    |     at tryModuleLoad (module.js:446:12)
1|proxy    |     at Function.Module._load (module.js:438:3)
1|proxy    |     at Module.require (module.js:497:17)
1|proxy    |     at require (internal/module.js:20:19)
1|proxy    |     at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/proxy.js:9:17)
1|proxy    |     at Module._compile (module.js:570:32)
1|proxy    |     at Object.Module._extensions..js (module.js:579:10)
```

**Comment by passnet** [comment]
It's pretty self-explanatory. Your config has syntax error. Check your configuration for errors like having extra or missing comma after brackets, etc. See config-example.json for reference.
