### ISSUE TITLE
Running on i386

### ISSUE THREAD

**Issue by MigzuASD** [Snipa22/xmr-node-proxy#65]
I'd like to know if it is possible to run this software on 32 bit linux.
I did everything according to the guide, used the non-aes-ni multihashing and got no compile errors of any kind. When I try running the proxy, my log fills with the following error:

`Cluster master setting up 1 workers...
Error: /home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util/build/Release/cryptonote.node: undefined symbol: cn_slow_hash
at Error (native)
at Object.Module._extensions..node (module.js:597:18)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at bindings (/home/nodeproxy/xmr-node-proxy/node_modules/bindings/bindings.js:81:44)
at Object.<anonymous> (/home/nodeproxy/xmr-node-proxy/node_modules/cryptonote-util/index.js:1:99)
at Module._compile (module.js:570:32)
`
(I can't get line breaks to work correctly, sorry about that)

I've used the same installation procedure on a different computer succesfully. The only obvious difference is the processor bitness. Is there a workaround for this problem or is 32-bit running impossible?

**Comment by Snipa22** [comment]
Non-supported overall, we're using alot of fairly large integers and working on this.  In general, I'd stick to x86_64.

**Comment by untoreh** [comment]
trying to run on alpine I get the same error when starting the proxy after succesful compilation, along with `generate_random_bytes` and the rest of the gibberish :), I also did a successful compilation under `alpine:3.2` which was the last release with libboost `1.58` but the log is the same:
```
$ ldd ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node
        ldd (0x7fa422afd000)
        libboost_system.so.1.62.0 => /usr/lib/libboost_system.so.1.62.0 (0x7fa422687000)
        libboost_date_time.so.1.62.0 => /usr/lib/libboost_date_time.so.1.62.0 (0x7fa422476000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fa422124000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fa421f12000)
        libc.musl-x86_64.so.1 => ldd (0x7fa422afd000)
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v814ObjectTemplate21SetInternalFieldCountEi: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v820EscapableHandleScope6EscapeEPPNS_8internal6ObjectE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v88External3NewEPNS_7IsolateEPv: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZNK2v88External5ValueEv: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v811HandleScopeC1EPNS_7IsolateE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v820EscapableHandleScopeC1EPNS_7IsolateE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v811HandleScopeD1Ev: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: cn_slow_hash: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v87Isolate10GetCurrentEv: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN4node6Buffer4DataEN2v85LocalINS1_6ObjectEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZNK2v85Value8ToUint32ENS_5LocalINS_7ContextEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v86Object20SlowGetInternalFieldEi: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v87Integer15NewFromUnsignedEPNS_7IsolateEj: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v86Object3SetENS_5LocalINS_7ContextEEENS1_INS_5ValueEEES5_: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v89Exception5ErrorENS_5LocalINS_6StringEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN4node6Buffer4CopyEPN2v87IsolateEPKcm: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v811HandleScope12CreateHandleEPNS_8internal10HeapObjectEPNS1_6ObjectE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN4node6Buffer6LengthEN2v85LocalINS1_6ObjectEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v87Isolate14ThrowExceptionENS_5LocalINS_5ValueEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v87Isolate17GetCurrentContextEv: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v86Object16SetInternalFieldEiNS_5LocalINS_5ValueEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v86String11NewFromUtf8EPNS_7IsolateEPKcNS_13NewStringTypeEi: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v814ObjectTemplate3NewEPNS_7IsolateENS_5LocalINS_16FunctionTemplateEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v82V812ToLocalEmptyEv: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: node_module_register: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZNK2v85Value8IsNumberEv: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZNK2v85Value8ToObjectENS_5LocalINS_7ContextEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN4node6Buffer11HasInstanceEN2v85LocalINS1_6ObjectEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v816FunctionTemplate11GetFunctionENS_5LocalINS_7ContextEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v811HandleScopeD2Ev: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZN2v814ObjectTemplate11NewInstanceENS_5LocalINS_7ContextEEE: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: generate_random_bytes: symbol not found
Error relocating ./node_modules/cryptoforknote-util/build/Release/cryptoforknote.node: _ZNK2v85Value10Int32ValueENS_5LocalINS_7ContextEEE: symbol not found
```
