### ISSUE TITLE
pm2 not installed, npm not installed

### ISSUE THREAD

**Issue by kyleboddy** [Snipa22/xmr-node-proxy#78]
When running the script, npm/pm2 are not installed.

Installing them works and starting the proxy seems to work but gives these responses, and then client xmr-stak will not connect to the proxies either.

Did dependencies change?

```
ubuntu@xxxxxx~/xmr-node-proxy$ pm2 start proxy.js --name=proxy --log-date-format="YYYY-MM-DD HH:mm Z"
[PM2] Starting /home/ubuntu/xmr-node-proxy/proxy.js in fork_mode (1 instance)
[PM2] Done.
ââââââââââââ¬âââââ¬âââââââ¬ââââââââ¬âââââââââ¬ââââââââââ¬âââââââââ¬ââââââ¬ââââââââââââ¬âââââââââ¬âââââââââââ
â App name â id â mode â pid   â status â restart â uptime â cpu â mem       â user   â watching â
ââââââââââââ¼âââââ¼âââââââ¼ââââââââ¼âââââââââ¼ââââââââââ¼âââââââââ¼ââââââ¼ââââââââââââ¼âââââââââ¼âââââââââââ¤
â proxy    â 1  â fork â 20417 â online â 0       â 0s     â 0%  â 12.2 MB   â ubuntu â disabled â
ââââââââââââ´âââââ´âââââââ´ââââââââ´âââââââââ´ââââââââââ´âââââââââ´ââââââ´ââââââââââââ´âââââââââ´âââââââââââ
 Module activated
âââââââââââââââââ¬ââââââââââ¬âââââââââââââ¬âââââââââ¬ââââââââââ¬ââââââ¬ââââââââââââââ¬âââââââââ
â Module        â version â target PID â status â restart â cpu â memory      â user   â
âââââââââââââââââ¼ââââââââââ¼âââââââââââââ¼âââââââââ¼ââââââââââ¼ââââââ¼ââââââââââââââ¼âââââââââ¤
â pm2-logrotate â 2.4.0   â N/A        â online â 0       â 0%  â 41.977 MB   â ubuntu â
âââââââââââââââââ´ââââââââââ´âââââââââââââ´âââââââââ´ââââââââââ´ââââââ´ââââââââââââââ´âââââââââ
 Use `pm2 show <id|name>` to get more details about an app
ubuntu@xxxxxxx:~/xmr-node-proxy$ pm2 save
[PM2] Saving current process list...
[PM2] Successfully saved in /home/ubuntu/.pm2/dump.pm2
ubuntu@xxxxxxx:~/xmr-node-proxy$ pm2 logs proxy
[TAILING] Tailing last 15 lines for [proxy] process (change the value with --lines option)
/home/ubuntu/.pm2/logs/proxy-out-1.log last 15 lines:
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...
1|proxy    | 2017-12-18 04:06 +00:00: Cluster master setting up 1 workers...

/home/ubuntu/.pm2/logs/proxy-error-1.log last 15 lines:
1|proxy    |     at bindings (/home/ubuntu/xmr-node-proxy/node_modules/bindings/bindings.js:81:44)
1|proxy    |     at Object.<anonymous> (/home/ubuntu/xmr-node-proxy/node_modules/multi-hashing/index.js:1:99)
1|proxy    |     at Module._compile (module.js:410:26)
1|proxy    |     at Object.Module._extensions..js (module.js:417:10)
1|proxy    | 2017-12-18 04:06 +00:00: Error: Module version mismatch. Expected 46, got 48.
1|proxy    |     at Error (native)
1|proxy    |     at Object.Module._extensions..node (module.js:435:18)
1|proxy    |     at Module.load (module.js:344:32)
1|proxy    |     at Function.Module._load (module.js:301:12)
1|proxy    |     at Module.require (module.js:354:17)
1|proxy    |     at require (internal/module.js:12:17)
1|proxy    |     at bindings (/home/ubuntu/xmr-node-proxy/node_modules/bindings/bindings.js:81:44)
1|proxy    |     at Object.<anonymous> (/home/ubuntu/xmr-node-proxy/node_modules/multi-hashing/index.js:1:99)
1|proxy    |     at Module._compile (module.js:410:26)
1|proxy    |     at Object.Module._extensions..js (module.js:417:10)
```

**Comment by kyleboddy** [comment]
This is due to me being an idiot and not switching over to the `nodeproxy` user before installing.
