### ISSUE TITLE
pm2: command not found

### ISSUE THREAD

**Issue by isheirff** [Snipa22/xmr-node-proxy#92]
i am gettting this error pm2: command not found

please help, i have the config file and all other files in the folder, but says command not found

**Comment by isheirff** [comment]
okay i had to login to as the same user that installed it, however i am getting these errors

|proxy    |     at emitTwo (events.js:111:20)
1|proxy    |     at process.emit (events.js:191:7)
1|proxy    |     at process.nextTick (internal/child_process.js:744:12)
1|proxy    |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
1|proxy    | 2018-01-09 13:58 -05:00: Worker 10069 died with code: 1, and signal: null
1|proxy    | Starting a new worker
1|proxy    | 2018-01-09 13:58 -05:00: Error: bind EACCES 0.0.0.0:80
1|proxy    |     at Object.exports._errnoException (util.js:1022:11)
1|proxy    |     at exports._exceptionWithHostPort (util.js:1045:20)
1|proxy    |     at cb (net.js:1324:16)
1|proxy    |     at rr (cluster.js:625:14)
1|proxy    |     at Worker.<anonymous> (cluster.js:594:9)
1|proxy    |     at process.<anonymous> (cluster.js:765:8)
1|proxy    |     at emitTwo (events.js:111:20)
1|proxy    |     at process.emit (events.js:191:7)
1|proxy    |     at process.nextTick (internal/child_process.js:744:12)
1|proxy    |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
1|proxy    | 2018-01-09 13:58 -05:00: Worker 10102 died with code: 1, and signal: null
1|proxy    | Starting a new worker
1|proxy    | 2018-01-09 13:58 -05:00: Worker 10177 is online
1|proxy    | 2018-01-09 13:58 -05:00: Worker 10188 is online
1|proxy    | 2018-01-09 13:58 -05:00: Error: bind EACCES 0.0.0.0:80
1|proxy    |     at Object.exports._errnoException (util.js:1022:11)
1|proxy    |     at exports._exceptionWithHostPort (util.js:1045:20)
1|proxy    |     at cb (net.js:1324:16)

someone please help

**Comment by passnet** [comment]
You are trying to listen on port 80 which are privileged (<1024). Only root can listen on privileged port by default. Either change your port to >1024 or check this manual to allow your proxy user to listed on privileged port: https://unix.stackexchange.com/questions/10735/linux-allowing-an-user-to-listen-to-a-port-below-1024
